### PR TITLE
Add support for typed arrays

### PR DESCRIPTION
**Pull request by Y--**
Hi @torch2424!

Here is a small contribution to your awesome library!

* add binding from `Array`s `[1, 2, 3]` to `Array<i32>`
* add support for `Array`s of `String` such as `["a", "b", "c"]`
* add support for `Array`s of `Boolean` `[true, false, true]`
* add support for `"BigInt64Array", "BigUint64Array"`
* add support for `Array`s of `Array`

You will note that for Arrays we're doing discovery based on the first element only (for obvious performance reasons).
Happy to discuss it here if need be.

### CODE REVIEW

**Comment by torch2424** [comment]
@Y-- Hello! Ah this PR is awesome! :smile: Thank you SOOOOO much for this! :smile: :tada: 

So looking at the code, this all looks great! Thank you so much for this! I think we should update a couple more places though (if you would like I could do this, but I think it'd be easier to update your PR :) ):

* We should update the return types, that way users can specify their expected return type as one of these types: https://github.com/torch2424/as-bind/blob/master/lib/asbind-instance/supported-ref-types.js#L208 

* We should update the table on the README with the new types: https://github.com/torch2424/as-bind/blob/master/README.md#supported-data-types (This one I especially am happy to do in a seperate PR, since I could remove the NOTE, and I have a github table maker thing :smile:, and then release a new version right after )

Thanks again! :smile: :tada:

**Comment by Y--** [comment]
Thanks a lot for your quick and positive review!
First, let me start by saying that all the credit goes to @maxime-petitjean, he's the main author here! I just pushed the PR button :-)

We'll work on your suggestions tomorrow and submit an updated version asap!

Cheers!

**Comment by Y--** [comment]
> * We should update the return types, that way users can specify their expected return type as one of these types: https://github.com/torch2424/as-bind/blob/master/lib/asbind-instance/supported-ref-types.js#L208

I've just pushed a commit that auto-generate the list based on the export above: https://github.com/sutoiku/as-bind/commit/2e8f33d12a9310c76353afc784b79d657e6f3e21
Let me know if that works for you or if you prefer an explicit list.

> * We should update the table on the README with the new types: https://github.com/torch2424/as-bind/blob/master/README.md#supported-data-types (This one I especially am happy to do in a seperate PR, since I could remove the NOTE, and I have a github table maker thing 😄, and then release a new version right after )

Given there is now many more supported types than the 4 context, I wonder if we shouldn't transpose the table to ease readability?
And if you have a tool to generate the table, I'm going to take you up on that offer and let you update it in a follow-up PR :-)

Thanks!!

**Review by aminya — APPROVED** [review]
Thanks for this nice PR. 

Could you update the readme with the new supported types?
https://github.com/sutoiku/as-bind#supported-data-types

**Comment by torch2424** [comment]
@Y-- Oops! I didn't see the updates yesterday!

> I've just pushed a commit that auto-generate the list based on the export above: sutoiku@2e8f33d . Let me know if that works for you or if you prefer an explicit list.

Oh! Today I learned you can update an export after you export it. I don't know why I had assumed that you couldn't :joy: Thank you! Yes I'd definitely prefer this!

> Given there is now many more supported types than the 4 context, I wonder if we shouldn't transpose the table to ease readability? And if you have a tool to generate the table, I'm going to take you up on that offer and let you update it in a follow-up PR :-)

Ah yeah, the table is going to get quite large :thinking: I opened an issue here to discuss how we might represent that: 

---

@aminya Thanks! Yeah I'm going to do a little follow up PR to update the Readme and things, since I'll need to publish a new version anyways. 

---

Thanks everyone! I super appreciate the PR! Approving and merging! :smile: :tada:

**Review by torch2424 — APPROVED** [review]

**Comment by Y--** [comment]
Thanks a lot!

**Comment by torch2424** [comment]
Published as 0.6.1 on npm and github! :smile: https://github.com/torch2424/as-bind/releases/tag/0.6.1

**Pull request merged**
